{
    "openapi": "3.0.0",
    "info": {
        "title": "Lysei Documentation",
        "description": "Essa é uma API para uso do LyseiApp",
        "version": "1.0.0",
        "contact": {
            "email":"ymoraisjaques@gmail.com"
        }
    },
    "paths": {
        "/sessions": {
            "post": {
                "tags": ["Session"],
                "summary": "User authentication",
                "description": "User authentication",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {                        
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQxNjc2NjQsImV4cCI6MTYyNDE4MjA2NCwic3ViIjoiNDQ3MGJhYTctMTE5NS00MDJlLWI5NjAtN2FhZDY0M2U0N2M4In0.oYez1gZkvATDwnKKqsBMcmcTwgqJsvSjY-UpeFjTJsM",
                                        "user": {
                                          "name": "Teste",
                                          "email": "teste@teste.com"
                                        },
                                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inltb3JhaXNqYXF1ZXNAZ21haWwuY29tIiwiaWF0IjoxNjI0MTY3NjY0LCJleHAiOjE2MjQxNzQ4NjQsInN1YiI6IjQ0NzBiYWE3LTExOTUtNDAyZS1iOTYwLTdhYWQ2NDNlNDdjOCJ9.2LXgksxLpnzqwdg-VyqIJFpiMlqTSaaXIzBTqV3tSk0"
                                    }                                
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Email or password incorrect"
                    }
                }
            }
        },
        "/refresh-token": {
            "post": {
                "tags": ["Refresh-token"],
                "summary": "User authentication refresh-token",
                "description": "Refresh-token for user session renovation",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "refresh-token": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inltb3JhaXNqYXF1ZXNAZ21haWwuY29tIiwiaWF0IjoxNjI0MTIwMTQ1LCJleHAiOjE2MjQxMjczNDUsInN1YiI6ImY1ZTY1YWFmLTNjNGQtNGIwMS1hOWNkLTMxYzBjMDVhMmFlZSJ9.S8SY_CC5qxYHHv_VEDWD5BVI4KyEH4cTkI_x_HLZEkY"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {                        
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inltb3JhaXNqYXF1ZXNAZ21haWwuY29tIiwiaWF0IjoxNjI0MTY3NzYyLCJleHAiOjE2MjQxNzQ5NjIsInN1YiI6IjQ0NzBiYWE3LTExOTUtNDAyZS1iOTYwLTdhYWQ2NDNlNDdjOCJ9.MXEz7deVUiJJ06UfCJGW3JC9Zn1VAzfs85LJS2JFyew",
                                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQxNjc3NjIsImV4cCI6MTYyNDE4MjE2Miwic3ViIjoiNDQ3MGJhYTctMTE5NS00MDJlLWI5NjAtN2FhZDY0M2U0N2M4In0.4iVn3v9IiNpREYL9QpPkQ97rHYDcHFiTpjAgpLgM8zU"
                                    }                                
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Refresh Token does not exist!"
                    }
                }
            }
        },
        "/users": {
            "post": {
                "tags": ["User"],
                "summary": "Create a user",
                "description": "Creates a new user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "password": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "cpf": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "email": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "state": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "city": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "isPolitician": {
                                        "type": "string",
                                        "required": false
                                    },
                                    "occupation": {
                                        "type": "string",
                                        "required": false
                                    }
                                },
                                "example": {
                                    "name": "Test",	
                                    "password": "1234",
                                    "cpf": "000000000000",
                                    "email": "test@test.com",
                                    "state": "AM",
                                    "city": "Taubaté",
                                    "isPolitician": "false",
                                    "occupation": "teste"
                                }
                            }
                        }
                    },
                    "required": "true",
                    "description": "Required fields"
                },
                "responses": {
                    "201": {
                        "description": "User created"                   
                    },
                    "400": {
                        "description": "User already exists!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "User already exists!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            },             
            "patch": {
                "tags": ["User"],
                "summary": "Update user profile",
                "description": "User must be authenticated",
                "security": [
                    { "bearerAuth": []}
                ],               
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "required": true
                                    },                                  
                                    "cpf": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "email": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "state": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "city": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "isPolitician": {
                                        "type": "string",
                                        "required": false,
                                        "default": false
                                    },
                                    "Occupation": {
                                        "type": "string",
                                        "required": false,
                                        "default": null
                                    }
                                },
                                "example": {
                                    "name": "Test",
                                    "cpf": "000000000000",
                                    "email": "test@test.com",
                                    "state": "AM",
                                    "city": "Taubaté",
                                    "isPolitician": false,
                                    "occupation": null
                                }
                            }
                        }
                    }                    
                },
                "responses": {
                    "201": {
                        "description": "Updated"                   
                    },
                    "400": {
                        "description": "Email or CPF already in use!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Email or CPF already in use!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/profile": {
            "get": {
                "tags": ["User"],
                "summary": "Show user profile",
                "description": "User must be authenticated. Can only be accessed by the actual user",
                "security": [
                    { "bearerAuth": []}
                ],               
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "name": {
                                            "type": "string",
                                            "required": true
                                        },
                                        "email": {
                                            "type": "string",
                                            "required": true
                                        }
                                    },
                                    "example": {
                                        "name": "Teste",
                                        "cpf": "00000000000",
                                        "email": "teste@teste.com",
                                        "avatar": "9efsfsdgcd0377b7ceb9bb726f12e0b-1564313132932.jpeg",
                                        "avatar_url": "https://api-lysei.s3.sa-east-1.amazonaws.com/avatar/9e456416717ccd039b7ceb9bb726f12e0b-15146543132932.jpeg",
                                        "state": "AM",
                                        "city": "Taubaté",
                                        "isPolitician": false,
                                        "occupation": null,
                                        "created_at": "2021-06-20T04:53:51.095Z"
                                    }                                
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Invalid token!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Invalid token!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            } 
        },
        "/users/checkEmailAvailability/:email": {
            "get": {
                "tags": ["User"],
                "summary": "Check email availability",   
                "parameters": [
                    {
                        "in": "path",
                        "name": "email",
                        "schema": {                        
                            "type": "string"                            
                        },                      
                        "required": "true"
                    }
                ],              
                "responses": {
                    "200": {
                        "description": "Email available!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {                                   
                                        "email": {
                                            "type": "string",
                                            "required": true
                                        }
                                    },
                                    "example": {
                                        "message": "Email available!"
                                    }                                
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Email already in use!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "message": "Email already in use!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            } 
        },
        "/users/resetPassword": {
            "patch": {
                "tags": ["User"],
                "summary": "Update user password",
                "description": "User must be authenticated",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "password": {
                                        "type": "string",
                                        "required": true
                                    }
                                },
                                "example": {
                                    "password": "Test"                                   
                                }
                            }
                        }
                    }                    
                },
                "responses": {
                    "200": {
                        "description": "Updated"                   
                    },
                    "401": {
                        "description": "Invalid token!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Invalid token!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/avatar": {
            "patch": {
                "tags": ["User"],
                "summary": "Update user avatar",
                "description": "User must be authenticated",
                "security": [
                    { "bearerAuth": []}
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "avatar": {
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "format": "binary"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "No Content"                   
                    },
                    "401": {
                        "description": "Invalid token!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Invalid token!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/posts": {
            "post": {
                "tags": ["Post"],
                "summary": "User must be authenticated",
                "description": "Create a new post",
                "security": [
                    { "bearerAuth": []}
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "title": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "description": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "state": { 
                                        "type": "string"
                                    },
                                    "city": { 
                                        "type": "string"
                                    },
                                    "district" :{ 
                                        "type": "string"
                                    },
                                    "street" :{ 
                                        "type": "string"
                                    },
                                    "number" :{ 
                                        "type": "number"
                                    },
                                    "picture" :{ 
                                        "type": "string"
                                    },
                                    "video" :{ 
                                        "type": "string"
                                    },
                                    "latitude" :{ 
                                        "type": "number"
                                    },
                                    "longitude" :{ 
                                        "type": "number"
                                    }
                                },
                                "example": {
                                    "title": "Buraco na rua",
                                    "description": "teste",
                                    "state": "SP",
                                    "city": "Taubaté",
                                    "district": "Jaraguá",
                                    "street": "João Monteiro de Franca ",
                                    "number": 400,
                                    "latitude": 1.1,
                                    "longitude": 1.1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    }              
                }
            }
        },
        "/posts/list": {
            "post": {
                "tags": ["Post"],
                "summary": "List posts by city and state",
                "description": "User must be authenticated",
                "security": [
                    { "bearerAuth": []}
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "state": {
                                        "type": "string",
                                        "required": true
                                    },
                                    "city": {
                                        "type": "string",
                                        "required": true
                                    }
                                },
                                "example": {
                                    "state": "AM",
                                    "city": "Taubaté"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Success!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": [                                   
                                        {
                                        "id": "277006a7-ddc1-4ce6-8819-64422e21e7d1",
                                        "title": "Buraco na rua",
                                        "description": "teste",
                                        "solved": false,
                                        "likes": 0,
                                        "author_id": "4470baa7-1195-402e-b960-7aad643e47c8",
                                        "state": "AM",
                                        "city": "Taubaté",
                                        "district": "Rosário",
                                        "street": "Francisco Torres",
                                        "number": 400,
                                        "picture": null,
                                        "video": null,
                                        "latitude": 1.1,
                                        "longitude": 1.1,
                                        "created_at": "2021-06-20T06:24:11.002Z"
                                        },
                                        {
                                        "id": "e6825801-b2e7-4d68-bee7-d49bdab6868c",
                                        "title": "Escola em decadência",
                                        "description": "Escola antiga em decadência",
                                        "solved": false,
                                        "likes": 0,
                                        "author_id": "4470baa7-1195-402e-b960-7aad643e47c8",
                                        "state": "AM",
                                        "city": "Taubaté",
                                        "district": "Centro",
                                        "street": "Rua do Acampamento",
                                        "number": 900,
                                        "picture": null,
                                        "video": null,
                                        "latitude": 56.3,
                                        "longitude": 10043.7,
                                        "created_at": "2021-06-20T16:26:11.012Z"
                                        }
                                    ]                                    
                                }
                            }
                        }
                    },
                    "400": {

                    }
                }
            }
        },
        "/posts/listUserCreatedPosts/:user_id": {
            "get": {
                "tags": ["Post"],
                "summary": "List user created posts",
                "description": "User must be authenticated",
                "security": [
                    { "bearerAuth": []}
                ],  
                "parameters": [
                    {
                        "in": "path",
                        "name": "user_id",
                        "schema": {                        
                            "type": "string",
                            "format": "uuid"
                        },                      
                        "required": "true"
                    }
                ],           
                "responses": {
                    "200": {
                        "description": "Success!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": [                                   
                                        {
                                            "id": "fc7390a5-bb93-4f75-b40e-3bbb7c7f7814",
                                            "title": "Escola em decadência",
                                            "description": "Escola antiga em decadência",
                                            "solved": false,
                                            "likes": 2,
                                            "author_id": "317e8adf-2848-4d47-883c-fbf0dff2190c",
                                            "state": "AM",
                                            "city": "Taubaté",
                                            "district": "Centro",
                                            "street": "Rua do Acampamento",
                                            "number": 900,
                                            "latitude": 56.3,
                                            "longitude": 10043.7,
                                            "created_at": "2021-07-14T20:29:27.065Z",
                                            "images": [
                                              {
                                                "id": "e4d31899-c70e-4679-abeb-dbe8ae35d8fa",
                                                "image_name": "localhost:3333/posts/0f7abc3d2b0451b97cf437893e2f6d16-Screenshot from 2021-03-16 15-04-02.png"
                                              },
                                              {
                                                "id": "35af54cd-355f-442e-b3c3-6510ae99b5d6",
                                                "image_name": "localhost:3333/posts/d7c88eee19c7dc92eec42203e1f1353e-Captura de tela de 2021-06-27 11-45-50.png"
                                              }
                                            ],
                                            "author": {
                                              "id": "637b75a0-b3a3-492e-8808-1dc4664cc312",
                                              "name": "Yves Jaques",
                                              "avatar": "localhost:3333/avatar/d6dd59860178ed5e82638cf944544c3b-wats.jpg"
                                            },
                                            "userLiked": [
                                              {
                                                "id": "72456b96-7ccf-4251-b800-e69fec7d23f5",
                                                "created_at": "2021-07-21T14:29:12.047Z"
                                              }
                                            ],
                                            "userFavorited": []
                                          },
                                          {
                                            "id": "ae8e009a-96f7-43f5-93d7-f5ed90779188",
                                            "title": "Escola em decadência",
                                            "description": "Ponte caindo",
                                            "solved": false,
                                            "likes": 0,
                                            "author_id": "317e8adf-2848-4d47-883c-fbf0dff2190c",
                                            "state": "RS",
                                            "city": "Santana",
                                            "district": "Centro",
                                            "street": "Rua do Acampamento",
                                            "number": 900,
                                            "latitude": 56.3,
                                            "longitude": 10043.7,
                                            "created_at": "2021-07-14T22:09:00.030Z",
                                            "images": [],
                                            "author": {
                                              "id": "a7b21667-3c08-471a-a2a1-118bf3e14f28",
                                              "name": "Yves Jaques",
                                              "avatar": "localhost:3333/avatar/d6dd59860178ed5e82638cf944544c3b-wats.jpg"
                                            },
                                            "userLiked": [],
                                            "userFavorited": []
                                          },
                                          {
                                            "id": "49d74398-edf2-4245-a92e-d231d4c15fa7",
                                            "title": "Escola em decadência",
                                            "description": "Escola antiga em decadência",
                                            "solved": false,
                                            "likes": 0,
                                            "author_id": "317e8adf-2848-4d47-883c-fbf0dff2190c",
                                            "state": "AM",
                                            "city": "Taubaté",
                                            "district": "Centro",
                                            "street": "Rua do Acampamento",
                                            "number": 900,
                                            "latitude": 56.3,
                                            "longitude": 10043.7,
                                            "created_at": "2021-07-14T20:29:27.030Z",
                                            "images": [],
                                            "author": {
                                              "id": "f64a7104-1511-4478-9864-7d0e88fc98b3",
                                              "name": "Yves Jaques",
                                              "avatar": "localhost:3333/avatar/d6dd59860178ed5e82638cf944544c3b-wats.jpg"
                                            },
                                            "userLiked": [],
                                            "userFavorited": []
                                          }
                                    ]                                    
                                }
                            }
                        }
                    },
                    "400": {

                    }
                }
            }
        },
        "/posts/like/:post_id": {
            "patch": {
                "tags": ["Post"],
                "summary": "Like/Dislike a post",
                "description": "User must be authenticated",
                "security": [
                    { "bearerAuth": []}
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "post_id",
                        "schema": {                        
                            "type": "string",
                            "format": "uuid"
                        },                      
                        "required": "true"
                    }
                ],                
                "responses": {
                    "200": {
                        "description": "Updated"                   
                    },
                    "401": {
                        "description": "Invalid token!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Invalid token!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/posts/favorite/:post_id": {
            "patch": {
                "tags": ["Post"],
                "summary": "Favorite/Unfavorite a post",
                "description": "User must be authenticated",
                "security": [
                    { "bearerAuth": []}
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "post_id",
                        "schema": {                        
                            "type": "string",
                            "format": "uuid"
                        },                      
                        "required": "true"
                    }
                ],                
                "responses": {
                    "200": {
                        "description": "True = Favorited / False = Unfavorited"                   
                    },
                    "401": {
                        "description": "Invalid token!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Invalid token!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/posts/favorite/list": {
            "get": {
                "tags": ["Post"],
                "summary": "List user favorite posts",
                "description": "User must be authenticated",
                "security": [
                    { "bearerAuth": []}
                ],
                "responses": {
                    "200": {
                        "description": "Success!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": [
                                        {
                                          "id": "fc7390a5-bb93-4f75-b40e-3bbb7c7f7814",
                                          "title": "Escola em decadência",
                                          "description": "Escola antiga em decadência",
                                          "solved": false,
                                          "likes": 2,
                                          "author_id": "317e8adf-2848-4d47-883c-fbf0dff2190c",
                                          "state": "AM",
                                          "city": "Taubaté",
                                          "district": "Centro",
                                          "street": "Rua do Acampamento",
                                          "number": 900,
                                          "latitude": 56.3,
                                          "longitude": 10043.7,
                                          "created_at": "2021-07-14T20:29:27.065Z",
                                          "images": [
                                            {
                                              "id": "63ad3a7b-5a3e-4f02-ad50-cae1cdf9178b",
                                              "image_name": "localhost:3333/posts/d7c88eee19c7dc92eec42203e1f1353e-Captura de tela de 2021-06-27 11-45-50.png"
                                            },
                                            {
                                              "id": "50518316-a69e-47fc-b102-99c57578d754",
                                              "image_name": "localhost:3333/posts/0f7abc3d2b0451b97cf437893e2f6d16-Screenshot from 2021-03-16 15-04-02.png"
                                            }
                                          ],
                                          "author": {
                                            "id": "3aa55902-500b-423b-b9fc-acb28e3ec66f",
                                            "name": "Yves Jaques",
                                            "avatar": "localhost:3333/avatar/d6dd59860178ed5e82638cf944544c3b-wats.jpg"
                                          },
                                          "userLiked": [
                                            {
                                              "id": "487f5a00-c73b-4df0-be25-3d92e9f0f21c",
                                              "created_at": "2021-07-30T21:42:34.928Z"
                                            }
                                          ],
                                          "userFavorited": [
                                            {
                                              "id": "45c8eadb-8f33-41f5-bda2-4377cf0fa0e8",
                                              "created_at": "2021-08-01T15:06:56.068Z"
                                            }
                                          ]
                                        }
                                    ]                                    
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid token!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Invalid token!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/posts/conclude/:post_id": {
            "patch": {
                "tags": ["Post"],
                "summary": "Conclude/unconclude a post",
                "description": "User must be authenticated and a politician",
                "security": [
                    { "bearerAuth": []}
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "post_id",
                        "schema": {                        
                            "type": "string",
                            "format": "uuid"
                        },                      
                        "required": "true"
                    }
                ],                
                "responses": {
                    "200": {
                        "description": "Updated"                   
                    },
                    "401": {
                        "description": "Invalid token!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Invalid token!"
                                    }                                    
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "User is not a politician!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "User is not a politician!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/posts/images/:post_id": {
            "get": {
                "tags": ["Post"],
                "summary": "List images from a specific post",
                "description": "User must be authenticated",
                "security": [
                    { "bearerAuth": []}
                ], 
                "parameters": [
                    {
                        "in": "path",
                        "name": "post_id",
                        "schema": {                        
                            "type": "string",
                            "format": "uuid"
                        },                      
                        "required": "true"
                    }
                ],               
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",                                   
                                    "example": [
                                        "localhost:3333/posts/4070d72179e4b465d53e0af265ac1969.png",
                                        "localhost:3333/posts/7fe18c53eb67ad0c1f6cc01a0f8ba02c.jpeg"
                                      ]                                
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Invalid token!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Invalid token!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Post"],
                "summary": "Update post images",
                "description": "User must be authenticated and author of the post",
                "security": [
                    { "bearerAuth": []}
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "post_id",
                        "schema": {                        
                            "type": "string",
                            "format": "uuid"
                        },                      
                        "required": "true"
                    }
                ], 
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "images": {
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "format": "binary"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"                   
                    },
                    "401": {
                        "description": "Invalid token!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Invalid token!"
                                    }                                    
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "User is not the author of the post!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "User is not the author of the post!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/posts/:post_id": {
            "get": {
                "tags": ["Post"],
                "summary": "Show info from a specific post",
                "description": "User must be authenticated",
                "security": [
                    { "bearerAuth": []}
                ], 
                "parameters": [
                    {
                        "in": "path",
                        "name": "post_id",
                        "schema": {                        
                            "type": "string",
                            "format": "uuid"
                        },                      
                        "required": "true"
                    }
                ],               
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "name": {
                                            "type": "string",
                                            "required": true
                                        },
                                        "email": {
                                            "type": "string",
                                            "required": true
                                        }
                                    },
                                    "example": {
                                        "id": "d3a259c9-9dc3-419a-9b17-018650a9f024",
                                        "title": "Buraco na rua",
                                        "description": "teste",
                                        "solved": false,
                                        "likes": 0,
                                        "author_id": "f5e65aaf-3c4d-4b01-a9cd-31c0c05a2aee",
                                        "state": "AM",
                                        "city": "Taubaté",
                                        "district": "Rosário",
                                        "street": "Francisco Torres",
                                        "number": 400,
                                        "picture": null,
                                        "video": null,
                                        "latitude": 1.1,
                                        "longitude": 1.1,
                                        "created_at": "2021-06-19T21:04:58.005Z"
                                    }                                
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Invalid token!",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",                                    
                                    "example": {
                                        "error": "Invalid token!"
                                    }                                    
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {

    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}